version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=your_mongodb_connection_string
      - CLIENT_URL=http://localhost
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: 